var controlDataBase = function () {
  return {
    options: [
      { value: 1,
        type: "move",
        text: "move",
        commands: [],
        action: moveAction },
      { value: 1,
        type: "click",
        text: "click",
        commands: [
          { value: 1,
            type: "click",
            text: "once",
            action: { execute: function(){console.log("click once")}  }},
          { value: 1,
            type: "click",
            text: "continuous",
            commands: [
              { value: 1,
                type: "click",
                color: "#1f77b4",
                text: "cancel clicking",
                action: { execute: function(){console.log("cancel continuous clicking")}  }},
            ],
            action: { execute: function(){console.log("continuous clicking")} } }
        ],
        action: { execute: function(){console.log("click")}  }},
      { value: 1,
        type: "scroll",
        text: "scroll",
        commands: [
          { value: 1,
            type: "scroll",
            text: "up",
            action: { execute: function(){console.log("scroll up")}  }},
          { value: 1,
            type: "scroll",
            text: "down",
            action: { execute: function(){console.log("scroll down")}  }},
          { value: 1,
            type: "scroll",
            text: "left",
            action: { execute: function(){console.log("scroll left")}  }},
          { value: 1,
            type: "scroll",
            text: "right",
            action: { execute: function(){console.log("scroll right")} } }
        ],
        action: { execute: function(){console.log("scroll")}  }},
      { value: 1,
        type: "zoom",
        text: "zoom",
        commands: [
          { value: 1,
            type: "zoom",
            text: "in",
            action: { execute: function(){console.log("zoom in")}  }},
          { value: 1,
            type: "zoom",
            text: "out",
            action: { execute: function(){console.log("zoom out")} } }
        ],
        action: { execute: function(){console.log("zoom")}  }},
      { value: 1,
        type: "navigation",
        text: "navigation",
        commands: [
          { value: 1,
            type: "navigation",
            text: "back",
            action: { execute: function(){console.log("back")}  }},
          { value: 1,
            type: "navigation",
            text: "forward",
            action: { execute: function(){console.log("forward")}  }},
          { value: 1,
            type: "navigation",
            text: "home",
            action: { execute: function(){console.log("home")}  }},
          { value: 1,
            type: "navigation",
            text: "refresh",
            action: { execute: function(){console.log("refresh")} } }
        ],
        action: { execute: function(){console.log("navigation")} } }
    ]
  }
};
